name: Daniel Melcer

description: >
  Computer Science student at Northeastern University

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

# The description that will go into the meta tag
metadescription: >
  Computer Science student at Northeastern University.
  Experience with Java, Python, Smart Contract (Solidity/Web3) development and GPU computing.

sass:
  sass_dir: _sass
  style: compressed

contact:
  - type: email
    icon: envelope
    link: mailto:daniel@melcer.dev
    display: daniel@melcer.dev
  - type: linkedin
    icon: linkedin
    link: https://www.linkedin.com/in/dmelcer9
    display: dmelcer9
  - type: github
    icon: brands fa-github
    link: https://github.com/dmelcer9
    display: dmelcer9
  - type: mastodon
    icon: brands fa-mastodon
    link: "https://mstdn.social/@dmelcer9"
    display: "@dmelcer9@mstdn.social"

defaults:
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Daniel Melcer

highlighter: rouge

paginate: 5
paginate_path: "/blog/:num"

collections:
  projects:
  posts:
  url-shortener:
    output: True
